_example/main.tf
doc/doc.go
print/print.go

Making sure it's not marked as required when a default exists, instead `<map>` will show up to indicate the type.
I might add `--verbose` in the future to print these types.
closes #9

doc: fix map type

---

doc/doc.go
print/print.go

Hi all!
Amazing tool, been looking to use this for a while but just have had the time to dive into it now. Noticed a couple of things that seemed like low-hanging fruit to fix.
First off, I've never really ever used the `description` parameter in variables, taking a godoc-style approach to documenting both variables and outputs (ie: using top-level comments). IMO it breaks workflow to have to throw docs one place and then a different place for something that's very similar in nature. Hence, I made a little backwards-compatible change that allows for the use of comments *if* description is not specified.
Second off, it looks like if one has line breaks in descriptions, the resulting markdown is broken, as markdown tables require line breaks as `<br>` tags. So the (first) commit addresses …

Allow top-level comments for variables, and markdown line break fixes, list placeholder

---

doc/doc.go

As it stands, comments like the following actually capture the `#` as part of the comment text:
```hcl
output "something" {}
```

Strip # prefix from comments

---

Readme.md

Just got `terraform-docs` into Homebrew here: https://github.com/Homebrew/homebrew-core/pull/11768.

Add note about installing with Homebrew

---

doc/doc.go
print/print.go

I thought it would be really useful if it was possible to document the variable type in addition to the existing documentation. So I've added support :) 
Currently only markdown supported, but trivial to add to other outputs.

Add support for printing the variable 'type' in Markdown.

---

main.go
print/print.go

Terraform implies a variable being required if you don't specify a default value, see [1].
Only if you leave out a default value the above "Required" column becomes a meaning.
The reality is, we specify a lot of default values for variables that are indeed required
but for whom we provide a sane default.
Furthermore we also specify quite some default empty string values "" for variables
which indeed are required, but we still cannot leave them out to mark them as required,
because of limitations in terraform where those values are being used in ternary operators.
Therefore the "Required" markdown column is meaningless in a lot of use
cases. This fixes it by introducing a `--no-required` option for markdown
generation which simply does not print it. It defaults to
false to retain current …

*: add --no-required option

---

doc/doc.go

We have something like that in our terraform code:
```
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
output "out1" {
description = "Description of out1"
value       = "out1"
}
output "out2" {
description = "Description of out2"
value       = "out2"
}
```
If the comment is directly before our first output, the comment is considered as the description of out1 even if there is an explicit description. I think that explicit description should prevail over comment.

If there is a description on an output, it should be considered before the preceding comment

---

README.md
internal/pkg/doc/doc.go
internal/pkg/doc/doc_test.go
internal/pkg/doc/input.go
internal/pkg/doc/output.go
internal/pkg/doc/testdata/outputs.tf
internal/pkg/doc/testdata/variables.tf
internal/pkg/print/json/json.go
internal/pkg/print/json/json_test.go
internal/pkg/print/json/testdata/json-WithSorting.golden
internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/markdown_test.go
internal/pkg/print/markdown/testdata/markdown-WithRequired.golden
internal/pkg/print/markdown/testdata/markdown-WithSorting.golden
internal/pkg/print/pretty/pretty.go
internal/pkg/print/pretty/pretty_test.go
internal/pkg/print/print.go
internal/pkg/settings/settings.go
main.go

This pull request adds the `--no-sort` option to omit sorted rendering of inputs and outputs. This is useful when sorting distorts context, e.g., when `terraform-docs` is used to populate a form.

Add option --no-sort to omit sorted rendering of inputs and outputs.

---

internal/pkg/doc/doc.go

This pull request changes the method used for extracting the filename from the path to check if main.tf is being processed. The current `path` package used is not OS agnostic, whereas `filepath` is. See [Package Filepath](https://golang.org/pkg/path/filepath/) for further info.
#32 

Fix Main.tf Comment Handling on Windows

---

AUTHORS
Makefile

When `authors` target in `Makefile` is used committer's email is being used instead of actual author of the commit, as a result there were many rows added with wrong email addresses.

Fix authors target in Makefile to get 'Author''s email not 'Committer'

---

examples/variables.tf
internal/pkg/doc/doc_test.go
internal/pkg/print/json/testdata/json-WithSortByName.golden
internal/pkg/print/json/testdata/json-WithSortInputsByRequired.golden
internal/pkg/print/json/testdata/json.golden
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/document/testdata/document-WithAggregateTypeDefaults.golden
internal/pkg/print/markdown/document/testdata/document-WithRequired.golden
internal/pkg/print/markdown/document/testdata/document-WithSortByName.golden
internal/pkg/print/markdown/document/testdata/document-WithSortInputsByRequired.golden
internal/pkg/print/markdown/document/testdata/document.golden
internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/markdown/table/testdata/table-WithAggregateTypeDefaults.golden
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/markdown/table/testdata/table-WithSortByName.golden
internal/pkg/print/markdown/table/testdata/table-WithSortInputsByRequired.golden
internal/pkg/print/markdown/table/testdata/table.golden
internal/pkg/print/pretty/pretty_test.go

This PR esacpes pipe (`|`) while generating Markdown document or table.
List any existing issues this pull request resolves. #112 

Escape pipe character when generating Markdown

---

cmd/root.go
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/document/document_test.go
internal/pkg/print/markdown/document/testdata/document-WithEscapeName.golden
internal/pkg/print/markdown/document/testdata/document-WithRequired.golden
internal/pkg/print/markdown/document/testdata/document-WithSortByName.golden
internal/pkg/print/markdown/document/testdata/document-WithSortInputsByRequired.golden
internal/pkg/print/markdown/document/testdata/document.golden
internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/markdown/table/table_test.go
internal/pkg/print/markdown/table/testdata/table-WithEscapeName.golden
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/markdown/table/testdata/table-WithSortByName.golden
internal/pkg/print/markdown/table/testdata/table-WithSortInputsByRequired.golden
internal/pkg/print/markdown/table/testdata/table.golden
internal/pkg/settings/settings.go

This PR adds a new flag `--no-escape` to `markdown` (also its alias: `md`) commands to not escaping special characters. The issue has been discussed at length at #111 .
Note that the default behavior is that Markdown printer escapes the characters and you need to explicitly tell `terraform-doc` to not escape them.
Fixes #111 

Add --no-escape flag for Markdown printer

---

cmd/root.go
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/document/document_test.go
internal/pkg/print/markdown/document/testdata/document-WithIndentationAboveAllowed.golden
internal/pkg/print/markdown/document/testdata/document-WithIndentationBellowAllowed.golden
internal/pkg/print/markdown/document/testdata/document-WithIndentationOfFour.golden
internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/markdown/table/table_test.go
internal/pkg/print/markdown/table/testdata/table-WithIndentationAboveAllowed.golden
internal/pkg/print/markdown/table/testdata/table-WithIndentationBellowAllowed.golden
internal/pkg/print/markdown/table/testdata/table-WithIndentationOfFour.golden
internal/pkg/settings/settings.go

This PR adds support for controlling indentation of Markdown headers by adding `--indent` flag to `markdown document` and `markdown table` commands. The available values are `1, 2, 3, 4, 5, 6, 7` and the default value is `2`. Any value outside of this range will default to `2`.
Fixes #89 

Add support for controlling the indentation of Markdown headers

---

.golangci.yml
internal/pkg/hcl/hcl.go
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/markdown.go
internal/pkg/print/pretty/pretty_test.go

This PR enables new go linters and fixes the existing issues for some of them. The list of enabled linters are:
- govet
- golint
- misspell
- varcheck
- structcheck
- staticcheck
- errcheck
- unconvert
- unused

Enable new go linters and fix the existing issues

---

internal/pkg/print/json/json_test.go
internal/pkg/print/json/testdata/json.golden
internal/pkg/print/markdown/document/document_test.go
internal/pkg/print/markdown/document/testdata/document-WithEscapeName.golden
internal/pkg/print/markdown/document/testdata/document-WithIndentationAboveAllowed.golden
internal/pkg/print/markdown/document/testdata/document-WithIndentationBellowAllowed.golden
internal/pkg/print/markdown/document/testdata/document-WithIndentationOfFour.golden
internal/pkg/print/markdown/document/testdata/document-WithRequired.golden
internal/pkg/print/markdown/document/testdata/document.golden
internal/pkg/print/markdown/table/table_test.go
internal/pkg/print/markdown/table/testdata/table-WithEscapeName.golden
internal/pkg/print/markdown/table/testdata/table-WithIndentationAboveAllowed.golden
internal/pkg/print/markdown/table/testdata/table-WithIndentationBellowAllowed.golden
internal/pkg/print/markdown/table/testdata/table-WithIndentationOfFour.golden
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/markdown/table/testdata/table.golden
internal/pkg/print/pretty/pretty_test.go
internal/pkg/print/pretty/testdata/pretty.golden
internal/pkg/tfconf/input.go
internal/pkg/tfconf/module.go
internal/pkg/tfconf/output.go
internal/pkg/tfconf/position.go

While adding the support for Terraform 0.12 configuration in #113 we lost support for `--no-sort` functionality, this PR fixes that and adds it back and also removes the temporary hack we had to do for tests to not constantly failing.

Reimplement '--no-sort' to be compatible with Terraform 0.12 configuration

---

cmd/root.go
internal/pkg/print/pretty/pretty.go
internal/pkg/print/pretty/pretty_test.go
internal/pkg/print/pretty/testdata/pretty-NoColor.golden
internal/pkg/print/settings.go

This PR adds a new `--no-color` flag to `pretty` command. Using this flag results into a color-less output in the terminal, note that the output is completely plain text and color less and not using `\033[0m` (reset color character).
Fixes #78 

Add '--no-color' flag to 'pretty' command

---

cmd/root.go
internal/pkg/print/settings.go

As of Terraform 0.12, the default value of input variables are shown in full JSON format (if available) and `--with-aggregate-type-defaults` is not needed anymore. The flag is marked as soft deprecated and will get removed in the second release from now.

Mark '--with-aggregate-type-defaults' as deprecated

---

cmd/root.go
internal/pkg/print/json/json_test.go
internal/pkg/print/markdown/document/document_test.go
internal/pkg/print/markdown/table/table_test.go
internal/pkg/print/pretty/pretty_test.go
internal/pkg/print/settings.go
internal/pkg/tfconf/module.go

For simplicity we've decided to deprecated the old `--sort-inputs-by-required` flag to the simpler and more generic `--sort--by-required`. The deprecated flags will get removed second release from now.

Rename flag to '--sort-by-required'

---

internal/pkg/print/json/testdata/json-EscapeCharacters.golden
internal/pkg/print/json/testdata/json-NoHeader.golden
internal/pkg/print/json/testdata/json-NoOutputs.golden
internal/pkg/print/json/testdata/json-NoProviders.golden
internal/pkg/print/json/testdata/json-OnlyInputs.golden
internal/pkg/print/json/testdata/json-SortByName.golden
internal/pkg/print/json/testdata/json-SortByRequired.golden
internal/pkg/print/json/testdata/json.golden
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/pretty/pretty.go
internal/pkg/tfconf/input.go
internal/pkg/tfconf/module.go

JSON properties which are `nil` were dropped from being rendered instead of being shown as `key: ""` or `key: null`. This PR fixes that. If properties are not defined one of the following can happen:
- `type: ""` (in reality never should happen though)
- `description: ""`
- `default: null`
Fixes #158 

Show all JSON properties, empty or null

---

cmd/json.go
cmd/markdown.go
cmd/pretty.go

With Terraform 0.12 ability to generate output from file has been deprecated in favor of from folder which contains one or more `.tf` files.

Deprecate accepting files as commands param

---

internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/table/testdata/table-EscapeCharacters.golden
internal/pkg/print/markdown/table/testdata/table-IndentationAboveAllowed.golden
internal/pkg/print/markdown/table/testdata/table-IndentationBellowAllowed.golden
internal/pkg/print/markdown/table/testdata/table-IndentationOfFour.golden
internal/pkg/print/markdown/table/testdata/table-NoHeader.golden
internal/pkg/print/markdown/table/testdata/table-NoOutputs.golden
internal/pkg/print/markdown/table/testdata/table-NoProviders.golden
internal/pkg/print/markdown/table/testdata/table-OnlyInputs.golden
internal/pkg/print/markdown/table/testdata/table-SortByName.golden
internal/pkg/print/markdown/table/testdata/table-SortByRequired.golden
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/markdown/table/testdata/table.golden

Multi-lines block of code in `markdown table` format is being wrapped inside `<code><pre> ... </pre></code>` which seems to cause rendering issues in different Markdown Rendering Engines (e.g. GitHub has serious issues with this, but GitLab has limited issue, etc.) see https://github.com/segmentio/terraform-docs/issues/138#issuecomment-570936597 .
Removing `<code> ... </code>` wrap seems to fix this issue in different platforms. (this is still being validated but looks good at the moment)
Fixes #138 

Do not wrap multiline blocks in table with <code>

---

internal/pkg/print/json/testdata/json-EscapeCharacters.golden
internal/pkg/print/json/testdata/json-NoHeader.golden
internal/pkg/print/json/testdata/json-NoInputs.golden
internal/pkg/print/json/testdata/json-NoOutputs.golden
internal/pkg/print/json/testdata/json-NoProviders.golden
internal/pkg/print/json/testdata/json-OnlyInputs.golden
internal/pkg/print/json/testdata/json-OnlyProviders.golden
internal/pkg/print/json/testdata/json-SortByName.golden
internal/pkg/print/json/testdata/json-SortByRequired.golden
internal/pkg/print/json/testdata/json.golden
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/pretty/pretty.go
internal/pkg/tfconf/input.go
internal/pkg/tfconf/module.go
internal/pkg/tfconf/output.go
internal/pkg/tfconf/provider.go
internal/pkg/tfconf/string.go

This is an amendment of #160 . Setting empty properties in `outputs` and `providers` to `null` were missing in the original PR which was added here. Also This PR makes sure that if the property is `empty` it sets it to `null` rather than `""` (empty string)
Related to #158 

Show empty JSON properties, as 'null' for all types

---

internal/pkg/print/markdown/markdown.go

This PR normalizes multi-lines paragraph into known Markdown convention and adds `<space><space>` at the end of each line.
Fixes #167 

Add double space at the end of multi-lines paragraph

---

docs/formats/json.md
internal/pkg/print/json/testdata/json-EscapeCharacters.golden
internal/pkg/print/json/testdata/json-NoHeader.golden
internal/pkg/print/json/testdata/json-NoOutputs.golden
internal/pkg/print/json/testdata/json-NoProviders.golden
internal/pkg/print/json/testdata/json-OnlyInputs.golden
internal/pkg/print/json/testdata/json-SortByName.golden
internal/pkg/print/json/testdata/json-SortByRequired.golden
internal/pkg/print/json/testdata/json.golden
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/pretty/pretty.go
internal/pkg/tfconf/input.go
internal/pkg/tfconf/module.go
internal/pkg/tfconf/string.go

> If an input variable is defined as list with default value, terraform-docs v0.8.0 defines the array within the json string instead as a json list/ array. Terraform-lists should be json arrays and not defined within strings.
This is actually a regression in `v0.8.0` and this PR fixes it.
Fixes #172 

Show native map and list as default value in JSON

---

internal/pkg/print/markdown/document/testdata/document-EscapeCharacters.golden
internal/pkg/print/markdown/document/testdata/document-IndentationAboveAllowed.golden
internal/pkg/print/markdown/document/testdata/document-IndentationBellowAllowed.golden
internal/pkg/print/markdown/document/testdata/document-IndentationOfFour.golden
internal/pkg/print/markdown/document/testdata/document-NoInputs.golden
internal/pkg/print/markdown/document/testdata/document-NoOutputs.golden
internal/pkg/print/markdown/document/testdata/document-NoProviders.golden
internal/pkg/print/markdown/document/testdata/document-OnlyHeader.golden
internal/pkg/print/markdown/document/testdata/document-SortByName.golden
internal/pkg/print/markdown/document/testdata/document-SortByRequired.golden
internal/pkg/print/markdown/document/testdata/document-WithRequired.golden
internal/pkg/print/markdown/document/testdata/document.golden
internal/pkg/print/markdown/markdown.go
internal/pkg/print/markdown/table/testdata/table-EscapeCharacters.golden
internal/pkg/print/markdown/table/testdata/table-IndentationAboveAllowed.golden
internal/pkg/print/markdown/table/testdata/table-IndentationBellowAllowed.golden
internal/pkg/print/markdown/table/testdata/table-IndentationOfFour.golden
internal/pkg/print/markdown/table/testdata/table-NoInputs.golden
internal/pkg/print/markdown/table/testdata/table-NoOutputs.golden
internal/pkg/print/markdown/table/testdata/table-NoProviders.golden
internal/pkg/print/markdown/table/testdata/table-OnlyHeader.golden
internal/pkg/print/markdown/table/testdata/table-SortByName.golden
internal/pkg/print/markdown/table/testdata/table-SortByRequired.golden
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/markdown/table/testdata/table.golden

This PR fixes a regression added in #169 and only append double spaces at the end of lines of a paragraph. Lines of a paragraph are the ones:
- followed immediately by another line
- there's no empty lines between them
- the next line starts with a alphanumeric
This, for example, doesn't add any extra spaces at the end of a markdown list (all the lines start with `-`)
Fixes #178 

Add double space only at the end of paragraph lines

---

Makefile
go.mod
go.sum
internal/pkg/print/json/json_test.go
internal/pkg/print/markdown/document/document_test.go
internal/pkg/print/markdown/table/table_test.go
internal/pkg/print/pretty/pretty_test.go
internal/pkg/testutil/settings.go
vendor/github.com/imdario/mergo/.gitignore
vendor/github.com/imdario/mergo/.travis.yml
vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
vendor/github.com/imdario/mergo/LICENSE
vendor/github.com/imdario/mergo/README.md
vendor/github.com/imdario/mergo/doc.go
vendor/github.com/imdario/mergo/map.go
vendor/github.com/imdario/mergo/merge.go
vendor/github.com/imdario/mergo/mergo.go
vendor/modules.txt

This PR adds a new struct `TestSettings` which is being used in test functions, and it replaces all the duplicate repetitive definitions of `print.Settings` into predefined builder functions.
For example:
```go
// we can use
settings := testutil.Settings().WithSections().With(&print.Settings{
SortByName: true,
}).Build()
// instead of
settings := &print.Settings{
SortByName:    true,
EscapePipe:    true,
ShowHeader:    true,
ShowProviders: true,
ShowInputs:    true,
ShowOutputs:   true,
}
```

Add TestSettings for cleaner required Settings in tests

---

internal/pkg/print/json/json.go
internal/pkg/print/markdown/document/document.go
internal/pkg/print/markdown/table/table.go
internal/pkg/print/markdown/table/testdata/table-WithRequired.golden
internal/pkg/print/pretty/pretty.go
internal/pkg/print/pretty/testdata/pretty-NoInputs.golden
internal/pkg/print/pretty/testdata/pretty-NoOutputs.golden
internal/pkg/print/pretty/testdata/pretty-NoProviders.golden
internal/pkg/print/pretty/testdata/pretty-OnlyHeader.golden
internal/pkg/print/pretty/testdata/pretty-SortByName.golden
internal/pkg/print/pretty/testdata/pretty-SortByRequired.golden
internal/pkg/print/pretty/testdata/pretty.golden
internal/pkg/tfconf/input.go
internal/pkg/tfconf/provider.go
internal/pkg/tmpl/template.go

This PR refactors the way different printers work and introduces template rendering engine as opposed to `functions + buffer.WriteString` which have been heavily used. There are some benefits with this approach:
- the code is cleaner and smaller
- the templates are more human friendly
- as a result any changes in the layout would be more natural
For example this is part of a code for rendering `providers` in `table` format:
```tpl
{{- if .Settings.ShowProviders -}}
{{ indent 0 }} Providers
{{ if not .Module.Providers }}
No provider.
{{ else }}
| Name | Version |
|------|---------|
{{- range .Module.Providers }}
| {{ name …
```

Render formatted results with go templates

---

cmd/root.go
examples/output_values.json
internal/format/document.go
internal/format/json_test.go
internal/format/pretty.go
internal/format/table.go
internal/format/testdata/document/document-OutputValues.golden
internal/format/testdata/json/json-OutputValues.golden
internal/format/testdata/pretty/pretty-OutputValues.golden
internal/format/testdata/table/table-OutputValues.golden
internal/format/testdata/yaml/yaml-OutputValues.golden
internal/module/module.go
internal/types/types.go
pkg/tfconf/input.go
pkg/tfconf/output.go
pkg/tmpl/template.go

Following up #191 which adds the support for rendering output values extracted from `terraform output --json` command, this PR enhances it to show sensitivity of those outputs as well. e.g.
```json
{
...
"outputs": [
{
"name": "output-1",
"description": "It's output number one.",
"value": 1,
"sensitive": false
},
{
"name": "output-0.12",
"description": "terraform 0.12 only",
"value": "<sensitive>",
"sensitive": true
}
],
..
}
```
Note that the schema of `json` and `yaml` renderer is not changed when `--output-values` is not set. In other words properties `value` and `sensitive` are only available when `--output-values` is …

Show sensitivity of the output value in rendered result

---

docs/USER_GUIDE.md

resolves #180
Resolves discoverability issue in locating usage info and description of output formats.
The root [README.md](README.me) has no reference to [docs/README.md](docs/README.md) and only referred to [docs/USAGE_GUIDE.md](docs/USAGE_GUIDE.md) which only contained git hook info, but nothing about actually using the tool.
This PR resolves the issue, and takes a minimally-invasive approach to resolving basic discoverability of CLI usage and output format info. Previously you would have to know to ignore `README.md` and `docs/USAGE_GUIDE.md`, manually navigating to `docs/README.md`.
resolves #180 
Put an `x` into all …

Put reference to usage, cli, etc. in user guide

---

cmd/markdown.go
cmd/root.go
docs/formats/markdown-document.md
docs/formats/markdown-table.md
docs/formats/markdown.md
internal/format/document.go
internal/format/document_test.go
internal/format/table.go
internal/format/table_test.go
internal/format/testdata/document/document-OutputValuesNoSensitivity.golden
internal/format/testdata/table/table-OutputValuesNoSensitivity.golden
pkg/print/settings.go

Use case: for projects where all outputs are expected to not be sensitive, it adds noise. This PR adds the `--no-sensitive` option to the markdown generation command. This options removes the sensitive column. The column will show by default, this is an opt-out

Allow hiding the "Sensitive" column in markdown

---

cmd/root.go
internal/format/document_test.go
internal/format/json_test.go
internal/format/pretty_test.go
internal/format/table_test.go
internal/format/testdata/json/json-Empty.golden
internal/format/testdata/xml/xml-Empty.golden
internal/format/testdata/yaml/yaml-Empty.golden
internal/format/xml_test.go
internal/format/yaml_test.go
internal/module/module.go
internal/module/module_test.go
internal/module/options.go

Our projects do not have that file. Even with `--no-header`, terraform-docs crashes. This PR stops the tool from reading a file when `--no-header` is set.
I'm not sure if the test is in the correct location. Let me know if that works for you

--no-header should not attempt reading main.tf file

---

cmd/root.go
internal/module/module.go
internal/module/module_test.go

There was a regression added in #217 in which if there's no `main.tf` file available in the module, executing any commands of `terraform-docs` fails with `Error: open main.tf: no such file or directory` error. This PR handles the situation and:
- silently ignore the error if the file missing is `main.tf`
- shows error and exit 1 if the file missing is anything else (i.e. `--header-from` was explicitly set by the user)
Fixes #232 

Don't crash when reading header if 'main.tf' not found

---

Makefile
cmd/root.go
cmd/version.go
internal/format/asciidoc_document_test.go
internal/format/asciidoc_table_test.go
internal/format/factory_test.go
internal/format/json_test.go
internal/format/markdown_document_test.go
internal/format/markdown_table_test.go
internal/format/pretty_test.go
internal/format/tfvars_hcl_test.go
internal/format/tfvars_json.go
internal/format/tfvars_json_test.go
internal/format/toml.go
internal/format/toml_test.go
internal/format/xml_test.go
internal/format/yaml.go
internal/format/yaml_test.go
internal/module/input_test.go
internal/module/output_test.go
internal/module/provider_test.go
internal/testutil/settings.go
pkg/tfconf/input_test.go
pkg/tfconf/output_test.go
pkg/tfconf/provider_test.go
pkg/tmpl/sanitizer.go
pkg/tmpl/sanitizer_test.go
pkg/tmpl/template_test.go

Enforcing `goimports -local <string>` to put `terraform-docs` imports and packages after 3rd-party packages.

Put terraform-docs imports after 3rd-party packages

---

docs/CONFIG_FILE.md

This PR fixes typo (`markdonw` → `markdown`) in `docs/CONFIG_FILE.md`.
none

Fix typo in docs/CONFIG_FILE.md

---

.editorconfig
internal/module/module.go
internal/module/module_test.go
internal/module/testdata/inputs-crlf/variables.tf
internal/module/testdata/inputs-lf/variables.tf

This PR normalizes input variables which has CRLF as line ending in multi-line heredoc style description. It will convert them internally to LF early on and continue parsing and rendering them as usual.
Fixes #305 

Normalize variables with CRLF line ending in heredoc

---

.github/dependabot.yaml

Since terraform-docs uses GitHub actions and dependabot is now native to GitHub, it would be nice to keep those up-to-date automatically via dependabot. Below is an example of a basic dependabot.yaml which GitHub suggests. 
https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot#example-dependabotyml-file-for-github-actions
I believe this is not applicable since I'm not making changes to the actual script.
I believe this is not applicable since I'm not making changes to the actual script.
I believe this is not applicable …

Allow dependabot to update github action versions

---

internal/cli/reader.go
internal/cli/reader_test.go

This PR fixes a regression added in `v0.10.0` in which if the input arg is a file instead of a directory the terraform-docs crashes with `panic: runtime error: invalid memory address or nil pointer dereference` error instead of gracefully handle it.
Fixes #297 
Related to #325 

Prevent segfault error if input arg is a file

---

internal/version/version.go

When `brew` attempts to install the binary downloads a tarball and extract it and runs `make build` in it, at that point that folder is not a git repository hence `git describe tag` wouldn't return back the correct version. This PR ignores the default segment (i.e. `v0.0.0-`) as it should never happen.
Fixes #331 

Show correct version when brew installs it

---

docs/formats/tfvars-json.md
go.mod
go.sum
internal/format/testdata/tfvars/json-EscapeCharacters.golden
internal/format/testdata/tfvars/json-NoInputs.golden
internal/format/testdata/tfvars/json-SortByName.golden
internal/format/testdata/tfvars/json-SortByRequired.golden
internal/format/testdata/tfvars/json-SortByType.golden
internal/format/testdata/tfvars/json.golden
internal/format/tfvars_json.go

Due to limitation of `orderedmap`, special characters in `tfvars json` always were escaped which was fixed in https://github.com/iancoleman/orderedmap/pull/15, so now we're also never escaping special characters when generating `tfvars json` output.

Never escape special characters in tfvars json

---

CONTRIBUTING.md

Make sure commits sign-off and [Developer Certificate of Origin](https://developercertificate.org/) is part of the repository workflow.

Make Developer Certificate of Origin (DCO) a requirement

---

internal/template/sanitizer.go
internal/template/sanitizer_test.go

Originally '*' was included in illegal characters to be escaped,
specifically when formatter is markdown or asciidoc. But there's no
real point of escaping asterisk, as markdown engines will process them
properly.
Fixes #351 
I have:
Add corresponding test cases and make sure `make test` passes.

Do not escape asterisk in markdown or asciidoc

---

internal/cli/config.go

Fixes #387 
I have:
terraform-docs --show-all=false --show inputs md .  -> shows only `Inputs` section
terraform-docs --hide=modules md . -> shows all sections but `modules`

fixed modules section visibility set via commandline (#387)

---

internal/terraform/resource.go
internal/terraform/resource_test.go

Signed-off-by: Benjamin Ash <bash@intelerad.com>
With terraform-docs version v0.11.0 linux/amd64 BuildDate: 2021-02-14T17:33:17-05:00, the resource table is not rendered in a deterministic way when we have duplicate data and managed resources. This results in the following:
```
➜  falcon $ git diff README.md
platform-cluster/terraform/cluster on  feature/CPT-479-clouddr-eval-create-a-dedicated-utility-cluster-for-production! 17:32:23
➜  falcon $ ~/go/bin/terraform-docs md . > README.md && git diff README.md
platform-cluster/terraform/cluster on  feature/CPT-479-clouddr-eval-create-a-dedicated-utility-cluster-for-production! 17:32:35
➜  falcon $ ~/go/bin/terraform-docs md . > README.md && git diff README.md
platform-cluster/terraform/cluster on  …
```

include Resource.Mode when sorting to ensure deterministic resource table rendering

---

internal/terraform/resource.go
internal/terraform/resource_test.go

The big fix in #392 broke sort order for resources that have common prefix.
For example, after upgrading to 0.11.1, we see a flood of the following diffs in our modules:
```diff
| Name |
|------|
| [aws_iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/3.10/docs/data-sources/iam_policy_document) |
-| [aws_iam_role](https://registry.terraform.io/providers/hashicorp/aws/3.10/docs/resources/iam_role) |
-| [aws_iam_role_policy](https://registry.terraform.io/providers/hashicorp/aws/3.10/docs/resources/iam_role_policy) |
| [aws_iam_role_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/3.10/docs/resources/iam_role_policy_attachment) |
+| [aws_iam_role_policy](https://registry.terraform.io/providers/hashicorp/aws/3.10/docs/resources/iam_role_policy) …
```

Fixed lexicographic sorting of resources

---

cmd/asciidoc/asciidoc.go
cmd/json/json.go
cmd/markdown/markdown.go
cmd/pretty/pretty.go
cmd/root.go
internal/cli/config.go

In v0.10.0 flags '--no-XXX' have been deprecated in favor of their
counterparts in the format of '--X=false' (e.g. --no-header and
--header=false). And they are completely being removed now (two releases
after original announcement)
I have:
TBA.

Completely remove deprecated '--no-XXX' flags

---

.editorconfig
internal/format/asciidoc_document.go
internal/format/asciidoc_table.go
internal/format/markdown_document.go
internal/format/markdown_table.go
internal/format/pretty.go
internal/format/templates/asciidoc_document.tmpl
internal/format/templates/asciidoc_table.tmpl
internal/format/templates/markdown_document.tmpl
internal/format/templates/markdown_table.tmpl
internal/format/templates/pretty.tmpl
internal/format/templates/tfvars_hcl.tmpl
internal/format/tfvars_hcl.go

Embedding files was added in go1.16, so instead of defining required
templates as constant in .go files, they are moved to dedicated .tmpl
files.
I have:
No extra tests were added, all the existing tests were passed without any modification.

Use embedded template files

---

.pre-commit-hooks.yaml
docs/user-guide/how-to.md

Fixes #435
I did find the [existing instructions](https://terraform-docs.io/user-guide/how-to/#git-hook) on how to use a Git hook, and the references to [antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform), but I wanted to provide a pre-commit hook here, on this repo, so that users don't require a second repo just to use this tool via pre-commit.
I have:

#435: Add pre commit hook

---

cmd/root.go

This is a small change that prints any errors that surface when
executing the cli (i.e., `cmd.Execute()`) to stderr rather than
stdout.
When redirecting streams, its useful to keep errors separated from
program output so that in the case of an error the message won't be
redirected and is still surfaced. This issue came up for me when
using this terraform-docs in a script, where I encountered an error:
$ terraform-docs markdown path/not/to/mod > outfile
zsh: exit 1     terraform-docs markdown path/not/to/mod > outfile
When I ran the above command in my script an error was generated
because the path was incorrect, however the error message wasn't
printed to my console and the outfile was filled with the error
message. The change here modifies the cli's output to instead show:
$ …

print cli errors to stderr

---

internal/cli/config.go

This is to fix a small regression where footer-from isn't processed
properly, neither when it's passed via CLI flag nor in a config file.
Fixes #449 
I have:
Manually compiled and built the binary with the changes and tested for following and made sure the expected output was produced:
- `/bin/terraform-docs md tbl module/`
- `/bin/terraform-docs md tbl --footer-from footer.md module/`
- `/bin/terraform-docs module/` (with `.terraform-docs.yml`: `footer-from: ""`)
- `/bin/terraform-docs module/` (with `.terraform-docs.yml`: `footer-from: "footer.md"`)

Fix missing footer-from if set via CLI flag or config

---

cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
docs/user-guide/configuration.md
examples/.terraform-docs.yml
internal/cli/config.go
internal/cli/reader.go
internal/cli/reader_test.go

This deprecates sort by flags in favor of their corresponding dynamic
valued ones. Affected flags are:
- `--sort-by-required`
- `--sort-by-type`
In return new `--sort-by string` is added with following values:
- `name` (default)
- `required`
- `type`
Note that the behavior of `--sort bool` was not changed and to disable
sorting altogether you can run `--sort false`.
Fixes #448
I have:
No extra test is needed, just make sure the current ones pass.

Deprecate '--sort-by-XX' in favor of '--sort-by XX'

---

docs/user-guide/configuration.md
internal/cli/config.go

Some of the Markdown engines (e.g. Bitbucket Cloud) are not able to
process HTML comment but as a workaround they support variation of
inline comments as follow:
- ``
- `[]: # (This is a comment)`
- `[]: # "This is a comment"`
- `[]: # 'This is a comment'`
- `[//]: # (This is a comment)`
- `[comment]: # (This is a comment)`
The following is also supported for AsciiDoc format:
- `// This is a comment`
Fixes #463
I have:
Manually tested with multiple comment examples provided above.

Support inline comments variation for Markdown and AsciiDoc

---

docs/user-guide/configuration.md
examples/.terraform-docs.yml
go.mod
go.sum
internal/cli/config.go
internal/cli/run.go
internal/cli/run_test.go
internal/version/version.go

terraform-docs version constraints is almost identical to the syntax
used by Terraform. A version constraint is a string literal containing
one or more condition, which are separated by commas.
```yaml
version: ">= 0.13.0, < 1.0.0"
```
Each condition consists of an operator and a version number. A version
number is a series of numbers separated by dots (e.g. `0.13.0`). Note
that version number should not have leading `v` in it.
Valid operators are as follow:
- `=` (or no operator): allows for exact version number.
- `!=`: exclude an exact version number.
- `>`, `>=`, `<`, and `<=`: comparisons against a specific version.
- `~>`: only the rightmost version component to increment.
Fixes #343
I have:
Added new `TestVersionConstraint` set of tests.

Version constraints configuration

---

cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
docs/user-guide/configuration.md
docs/user-guide/how-to.md
internal/cli/writer.go
internal/cli/writer_test.go

`--output-file` or corresponding `output.file` config can now support
absolute path as well as relative path to root of module foler. For
example all of the followings are valid:
$ cd /path/to/module
$ tree .
.
├── docs
│   └── README.md
├── ...
└── main.tf
$ terraform-docs markdown table --output-file ../docs/README.md .
$ terraform-docs markdown table --output-file /path/to/module/docs/README.md .
Fixes #462
I have:
Manually built and tested all the relative/absolute combination, some specified in #462.

Support outputing to file for absolute path

---

docs/user-guide/configuration.md
internal/cli/testdata/writer/mode-inject-empty-file.golden
internal/cli/testdata/writer/mode-inject-file-missing.golden
internal/cli/testdata/writer/mode-inject-no-comment.golden
internal/cli/testdata/writer/mode-inject-no-comment.md
internal/cli/writer.go
internal/cli/writer_test.go

The following scenarios can happen for `--output-mode inject`:
- file exists, comments exist: inject output between comments
- file exists, comments not found: append output at the end of file
- file exists, but empty: save the whole output into the file
- file not found: create the target file and save the ooutput into it
I have:
Adjusted the test cases and added new ones (in `writer_test.go`)

In output-mode inject do not fail if file not found

---

internal/terraform/resource.go
internal/terraform/resource_test.go

fix for #492 bug. added missing field of the structure [Resource](https://github.com/terraform-docs/terraform-docs/blob/master/internal/terraform/resource.go#L22) the conversion method.
I have:
- [+] Read and followed terraform-docs' [contribution process].
- [+] All tests pass when I run `make test`.
within the fix new test provided.

Add missing Resource.Mode to plugin-sdk

---

.goreleaser.yml
Makefile
cmd/root.go
cmd/version/version.go
internal/cli/run.go
internal/version/version.go

As part of this normalization the following is made sure:
- leading `v` is shown in `-v, --version` and `version` command
- commit hash is shown in `-v, --version` and `version` command
- build date is removed
- version core (without pre-release) is used for constraint comparison
Fixes #495
I have:
- `go run` against `examples/` folder with `version` config enabled
- build with `make build` and run against `examples/` folder with `version` config enabled
- `go run main.go --version`
- build with `make build` and run with `--version`

Normalize version to prevent malformed error

---

go.mod
internal/terraform/module.go
internal/terraform/module_test.go
internal/terraform/testdata/with-lock-file/.terraform.lock.hcl
internal/terraform/testdata/with-lock-file/main.tf
internal/terraform/testdata/with-lock-file/outputs.tf
internal/terraform/testdata/with-lock-file/variables.tf

If .terraform.lock.hcl exists in module path, try to extract the exact
provider version being used as opposed to provided constraints.
Fixes #443 
I have:
- built and used against on module with existing `.terraform.lock.hcl`

Extract provider version from .terraform.lock.hcl

---

internal/format/util.go

Path separator of embed.FS is always a forward slash, even on Windows.
I have:
Manually built and tested on Windows.

Fix base template not found on Windows

---

docs/user-guide/how-to.md

changing file to include in the Include Example section of the How To Docs addressing Issue #512

updating how-to doc for correct Include Examples syntax

---

cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
docs/user-guide/configuration.md
docs/user-guide/how-to.md
internal/cli/config.go

In v0.13.0 flags `--sort-by-required` and `--sort-by-type` have been
deprecated in favor of `--sort-by required` and `--sort-by type`
respectively. And they are completely being removed now (two releases
after original announcement)
In v0.13.0 flags `--show-all` and `--hide-all` have been deprecated. And
they are completely being removed now (two releases after original
announcement)
New psuedo section `all` is added and can be used to show or hide _all_
sections. This can be used as a replacement for, now, deprecated and
removed `--show-all` and `--hide-all` flags.
I have:

Remove deprecated `--sort-by-XXX`, `--show-all`, and `--hide-all` flags

---

cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
internal/cli/config.go
internal/cli/run.go
internal/cli/writer.go
internal/cli/writer_test.go

**This is the exact copy of #458, which I accidentally closed!**
- Add a `--output-check` flag that only works when outputting to a file.
- Exit code 0 when no changes
- Exit code 1 when changes found
Also: 
- Return filename when output file updated (or differences found)
Fixes #456 
I have:

Add output-check flag option

---

cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
docs/user-guide/configuration.md
internal/cli/config.go
internal/terraform/module.go
internal/terraform/module_test.go
internal/terraform/options.go

New flag, `--lockfile`, is added to control whether ignore reading
`.terraform.lock.hcl` file in an attempt to extract the exact version of
provider being used or not. Default is true.
If set to true, exact version of provider available in lock file at the
time of execution will be extracted. If set to false, the version in `.tf`
file will be used (either exact, or a constrained version: >=, ~>, ...)
Fixes #517
I have:
New test case added to `TestLoadProviders` to read test module with the lockfile.

Ignore extracting versions from terraform.lock.hcl

---

internal/cli/config.go
internal/cli/config_test.go

When passing `--output-template` as CLI flag, `\n` is not processed as
line break rather than literal strings, which caused a misleading error
of "value of '--output-template' should contain at least 3 lines".
Fixes #536
I have:
Added all the new test cases in `config_test.go`.

Process \n as line break in --output-template flag

---

docs/user-guide/configuration.md
internal/cli/run.go

The updated order of trying to look up for .terraform-docs.yml config
file, now, is:
1. root of module directory
2. `.config/` folder at root of module directory
3. current directory
4. `.config/` folder at current directory
5. `$HOME/.tfdocs.d/`
Fixes #531
I have:
Manually created `.config/` folder in various places and made sure it is being picked up.

Attempt looking up config file in .config folder

---

go.mod
go.sum

Packer config, since 1.7.0, prefers HCL2 which effectively makes us to
reuse the same binary for generating documentation for it with terraform-docs
as well. The missing part was that terraform-config-inspect did not
recognize `pkr.hcl` and `pkr.json` as valid formats, which this fixes that.
Fixes #522
I have:
No new test added and all the existing ones should pass as is. This was also manually tested by @aston-r, https://github.com/terraform-docs/terraform-docs/issues/522#issuecomment-881263223.

Add support for generating Packer document

---

internal/template/sanitizer.go
internal/template/testdata/section/complex.expected
internal/template/testdata/section/complex.golden

If a code block (surrounded by triple backticks) are indented, in other
words the code block is placed inside ordered or unordered list, the
closing backticks of codeblock should honor the original indentation
properly.
Fixes #521 
I have:
Updated `complex.golden` test case to incorporate an indented code block and make sure the tests are passing.

Properly format indented code blocks

---

README.md
cmd/root.go
docs/reference/asciidoc-document.md
docs/reference/asciidoc-table.md
docs/reference/asciidoc.md
docs/reference/json.md
docs/reference/markdown-document.md
docs/reference/markdown-table.md
docs/reference/markdown.md
docs/reference/pretty.md
docs/reference/terraform-docs.md
docs/reference/tfvars-hcl.md
docs/reference/tfvars-json.md
docs/reference/tfvars.md
docs/reference/toml.md
docs/reference/xml.md
docs/reference/yaml.md
docs/user-guide/configuration.md
docs/user-guide/configuration/settings.md
internal/cli/config.go
internal/terraform/module.go
internal/terraform/module_test.go
internal/terraform/options.go
internal/terraform/testdata/read-comments/variables.tf
scripts/docs/generate.go

Fixes #552
This PR includes changes to optionally process comments from `.tf` files as description (when description is not provided in terraform inputs, outputs definition)
- Adds flag **`read-comments`** 
I have:
- Added test `TestReadComments()`
- Tested with `make test`
- Tested manually 
> **Manual Test**
> - Create sample tf folder and file
> ```
> mkdir /tmp/test-tf
> cat <<EOF >> /tmp/test-tf/sample.tf
> # some comment
> variable "var1" {
> }
> 
> # some comment
> output "output-var1" {
>   value = null
> }
> EOF
> ```
> 
> - Tested with read-comments as false. Expected - description should be n/a (should not use comment (#some comment) as description)
> ```go
> ▶ go run main.go --read-comments=false --show=inputs,outputs markdown /tmp/test-tf
> ```
> **Result:**
> ## Inputs
> 
> …

optionally process comments from tf files as description

---

README.md
cmd/root.go
docs/how-to/recursive-submodules.md
docs/user-guide/configuration.md
docs/user-guide/configuration/recursive.md
docs/user-guide/configuration/sections.md
docs/user-guide/configuration/settings.md
docs/user-guide/configuration/sort.md
examples/.terraform-docs.yml
internal/cli/run.go
print/config.go
print/config_test.go

Up to now there was only one way to enable recursive execution and that
was with `--recursive` CLI flag. This enables the same behavior but
within config file (i.e. `.terraform-docs.yml`)
Example:
```yaml
recursive:
enabled: false
path: modules
```
In the original implementation, when a submodule provided its
configuration it would completely override any config was provided by
its parent module. However with this approach the child module's
configuration will merge into its parent config and override any item
defined by both.
Example:
```
$ cat .terraform-docs.yml
formatter: markdown table
recursive:
enabled: true
sections:
show:
- header
- inputs
- outputs
output:
file: README.md
mode: inject
settings:
default: true
required: true
type: true
$ cat modules/module-b/.terraform-docs.yml …
```

Add recursive to config and enable partial config override

---

go.mod
go.sum
template/template.go

Add [Sprig](http://masterminds.github.io/sprig/) functions into built-in template functions. They can be used in `content` configuration.
xref: #549
I have:
Not applicable.

Add sprig functions to built-in template functions

---

README.md
docs/developer-guide/plugins.md
examples/.terraform-docs.yml
go.mod
go.sum
internal/cli/run.go
internal/plugin/discovery.go
internal/plugin/plugin.go
internal/types/types.go
plugin/client.go
plugin/doc.go
plugin/plugin.go
plugin/server.go
terraform/input.go
terraform/module.go
terraform/modulecall.go
terraform/output.go
terraform/provider.go
terraform/requirement.go
terraform/resource.go
terraform/resource_test.go

Moving terraform-docs/plugin-sdk standalone module to in-tree, because
maintaining both of them, specifically if anything needs to be added to
Config, or terraform will required dual effort on both repository. As
such now everything is consolidated under one repository. Example usage
for plugin developer after this move is as follow:
```go
package main
import (
_ "embed" //nolint
"github.com/terraform-docs/terraform-docs/plugin"
"github.com/terraform-docs/terraform-docs/print"
"github.com/terraform-docs/terraform-docs/template"
"github.com/terraform-docs/terraform-docs/terraform"
)
func main() {
plugin.Serve(&plugin.ServeOpts{
Name:    "template",
Version: "0.1.0",
Printer: printer,
})
}
//go:embed sections.tmpl
var tplCustom []byte
// Print the custom format template. You have all the …
```

Move plugin-sdk to in-tree in core repository

---

Makefile

From [GA runs](https://github.com/terraform-docs/terraform-docs/runs/7399944852?check_suite_focus=true) in #621, I realised the linter has been off, since the DNS for https://install.goreleaser.com no longer exists.
Switched it to the one liner suggested by the official `golangci-lint` guide: https://golangci-lint.run/usage/install/#linux-and-windows. And it happens to support version tag there too: https://github.com/golangci/golangci-lint/blob/4e60e8a894f113c23492c074c187e9bec1479463/install.sh#L14-L16, therefore just went with it.
I have:
Tested locally (darwin arm64) by removing my existing `golangci-lint` binary, and `make golangci`. Up to GA to test it out for real 😄.

Fix CI linting

---

Dockerfile
scripts/release/Dockerfile

This change upgrade the alpine base image used by terraform-docs from 3.16.0 to 3.16.1
Vulnerabilities flagged for alpine 3.16.0
```
terraform-docs:master (alpine 3.16.0)
Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 4, CRITICAL: 0)
┌──────────────┬────────────────┬──────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│   Library    │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                           Title                            │
├──────────────┼────────────────┼──────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ busybox      │ CVE-2022-30065 │ HIGH     │ 1.35.0-r13        │ 1.35.0-r15    │ busybox: A use-after-free in Busybox's awk applet leads to …
```

Update alpine to 3.16.1

---

Dockerfile
scripts/release/Dockerfile

This updates the container base images to a more recent version.
I have:
* `docker build -t my-terraform-docs .`
* `docker run --rm my-terraform-docs --version`

Update container to Alpine 3.18.2 and Go 1.18.10

---

docs/user-guide/configuration/content.md
docs/user-guide/configuration/output.md

Fix two typos in the documentation. Could not find any issue related to them.
I have:
Ran 'make test'. Looks good. Those are only documentation changes anyway.

docs: fix two typos in the 'configuration' section of the documentation

---

docs/user-guide/installation.md

Adds instructions for configuring `terraform-docs` completions with [`ohmyzsh`](https://ohmyz.sh/) shell.
I use `terragrunt`, `terraform`, `terraform-docs`, and `ohmyzsh` (with `terraform` plugin)
Versions:
* os: `Debian GNU/Linux 12 (bookworm)`
* `terraform-docs`: `terraform-docs version v0.17.0 795d369 linux/amd64`
* `omz`: `master (667fdbf)`
Steps:
* download latest binary for `linux/amd64`
* install `terraform-docs` into `/usr/bin/local`
* `omz reload` (makes `terraform-docs` available on `$PATH`)
* `terraform-docs completion zsh > ~/.oh-my-zsh/completions/_terraform-docs`
* `omz reload`
Results: 
* Tab completing `terra` within `terraform-docs` repository for this pr's fork.
* Tab completing `terraform-docs` shows options.
* Tab/Shift+Tab for selecting options.
---
closes #742

docs: document `terraform-docs` + `ohmyzsh` usage

---

cmd/completion/completion.go
docs/user-guide/installation.md
internal/cli/run.go

Added missing "s" character in binary name of the "bash completion CLI helptext" output.
I have:
Run `make test`. Since i'm not go developer i'm not sure why the tests of a "plain" repo clone on the master branch fails, but my branch also fails after the doc changes... ?!
```
PASS
coverage: 89.5% of statements
ok  	github.com/terraform-docs/terraform-docs/internal/types	0.006s	coverage: 89.5% of statements
FAIL	github.com/terraform-docs/terraform-docs/print [build failed]
FAIL	github.com/terraform-docs/terraform-docs/template [build failed]
FAIL	github.com/terraform-docs/terraform-docs/terraform [build failed]
make: *** [Makefile:77: test] Error 2
```

Fixed binary name in description output of bash completion generation cli command

---

Dockerfile
scripts/release/Dockerfile

This will set a non-ambiguous container source for the Dockerfile(s) used in this project. This reduces issues when using non-docker tooling that rely on full container sources. This increases not only verbosity but it also reduces the changes of exploits as explained in the following redhat post [Container image short names](https://www.redhat.com/sysadmin/container-image-short-names)
See also: https://github.com/terraform-docs/terraform-docs/issues/641
Fixes: #641 
I have:
I've tested it locally by running `make test` and was able to build the containers myself using `make docker`.

Update Dockerfile FROM command to use non-ambiguous container sources

---

docs/how-to/generate-terraform-tfvars.md
docs/how-to/github-action.md
docs/how-to/ignore-resources.md
docs/how-to/include-examples.md
docs/how-to/insert-output-to-file.md
docs/how-to/pre-commit-hooks.md
docs/how-to/recursive-submodules.md
examples/main.tf
examples/outputs.tf
examples/variables.tf
go.mod
terraform/load.go
terraform/load_test.go
terraform/testdata/full-example/main.tf
terraform/testdata/full-example/outputs.tf
terraform/testdata/full-example/variables.tf
terraform/testdata/read-comments/variables.tf

In our monorepo projects, we often have a set of variables that is shared amongst modules, eg. a `tags` variable that is accepted by all modules in the repo. This is typically done by symlinking a `common-vars.tf` file into all modules in the repo. This leads to those documentation these inputs being generated on every modules documentation.
This is not only rather repetitive, it also clutters the documentation by mixing the module specific inputs with the common ones, making it harder to read the module docs.
This PR introduces the possibility to add a comment `# terraform-docs-ignore` to a variable, telling `terraform-docs` to ignore and not render the variable in the documentation. 
Example:
```hcl
variable "tags" {
type        = map(string)
default     = {}
description = "A set of …
```

Ignore inputs with terraform-docs-ignore comment
