terraform-docs/terraform-docs

- print/print.go
also match last version output
> print: wrap default values

- doc/doc.go
- print/print.go
> Fix heredoc descriptions

- doc/doc.go
Very newb Go'er here, so let me know if this is terrible.
> Added sorting to inputs and outputs

- Readme.md
> Updated example in README

- Readme.md
- main.go
Currently it is only possible to specify directories.
This adds the possibility to add arbitrary files.
/cc @alexsomesan
> main: add support for files

- doc/doc.go
> Add support for reading `description` tag from `output` resources.

- print/print.go
> bugfix/#38 - default in input is broken with heredoc

- Readme.md
Martin Etmajer has offered to take over maintenance for this project. Explain that in the Readme.
> Add Maintenance section to Readme

- .circleci/config.yml
Adding a base CI config to test integration with segment's open source CircleCI account
> Add base CI config

- internal/pkg/doc/doc.go
- internal/pkg/doc/input.go
- internal/pkg/doc/output.go
- internal/pkg/print/markdown/markdown.go
- internal/pkg/print/pretty/pretty.go
This pull request refactors the 'doc' package to achieve more clarity through modularity with the goal to facilitate future code contributions.
- [] I have added tests to cover my changes.
- [x ] All tests pass when I run `make test`.
> Refactor package 'doc' for better modularity.

- README.md
There are minor Markdown lint issues in README (according to these [rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md)) which this pull request fixes them.
> Fix Markdown lint errors and enhancement in README

- .github/PULL_REQUEST_TEMPLATE.md
Add `This pull request enhances existing functionality` to `Prerequisites` section.
> Add 'enhancement' section to pull request template

- cmd/json.go
- cmd/markdown.go
- cmd/pretty.go
- cmd/root.go
- internal/pkg/print/json/json.go
- internal/pkg/print/json/json_test.go
- internal/pkg/print/markdown/document/document.go
- internal/pkg/print/markdown/document/document_test.go
- internal/pkg/print/markdown/markdown.go
- internal/pkg/print/markdown/table/table.go
- internal/pkg/print/markdown/table/table_test.go
- internal/pkg/print/pretty/pretty.go
- internal/pkg/print/pretty/pretty_test.go
- internal/pkg/print/print.go
- internal/pkg/settings/settings.go
This PR enhances `settings.Settings` and better use of pointer to get the better performance.
> Refactor Settings for better performance

- Makefile
- vendor/modules.txt
Describe what this pull request achieves. Ensure you have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md) document before submitting.
The deps target was removed from the makefile, but is still used by external scripts. Re-added as a link to the vendor target to maintain backward compatibility.
Fixes #125
> Fix missing deps make target

- .github/workflows/build.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- README.md
- go.mod
Bump golang version to latest v1.13 (1.13.5), as brew formula is already using it (https://github.com/Homebrew/homebrew-core/pull/47860)
> Bump golang to latest v1.13

- .github/workflows/release.yaml
- scripts/homebrew/README.md
- scripts/homebrew/terraform-docs.rb
Use [bump-homebrew-formula-action](https://github.com/mislav/bump-homebrew-formula-action) to automatically bump the homebrew formula on releasing a new version. This action will ignore pre-releases tags
> Bump homebrew formula version on release

- docs/README.md
- docs/formats/README.md
- docs/formats/json.md
- docs/formats/markdown-document.md
- docs/formats/markdown-table.md
- docs/formats/markdown.md
- docs/formats/pretty.md
Initial commit of in-repo documentation in `/docs` folder with usage and example command and output of various available types.
> Initial commit of usage documentation

- .github/workflows/release.yaml
- Makefile
- README.md
- scripts/release/release.sh
> Fix release scripts

- cmd/json.go
- cmd/markdown.go
- cmd/pretty.go
- cmd/root.go
- cmd/yaml.go
- internal/pkg/testutil/testing.go
- internal/pkg/tfconf/module.go
- internal/pkg/tfconf/options.go
- scripts/docs/generate.go
This PR adds a new struct `tfconf.Options` to encapsulate required options for loading a Module.
> Add tfconf.Options to load Module with

- .github/workflows/build.yaml
- codecov.yml
Describe what this pull request achieves. Ensure you have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md) document before submitting.
> Update Codecov config

- .github/workflows/build.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- Makefile
- README.md
- go.mod
- vendor/modules.txt
> Upgrade go to 1.14

- README.md
Adds guidance for installing via Windows, using the Chocolatey package manager.
n/a
> Add installation guide for Windows users

- internal/tfconfig/README.md
Following up the discussion https://github.com/hashicorp/terraform-config-inspect/issues/42#issuecomment-607301784 , adding a notice and a link back to the original `terraform-config-inspect` repository.
> Link to original terraform-config-inspect repo

- go.mod
- go.sum
Describe what this pull request achieves. Ensure you have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md) document before submitting.
> build(deps): bump github.com/spf13/cobra from 0.0.7 to 1.0.0

- README.md
s/doccs/docs/
Fixes some minor typos in the README.
> fix 'doccs' typo

- docs/USER_GUIDE.md
Add detail on extracting module header to user guide.
Fixes #278 
> Add detail about module header usage guide

- .github/workflows/build.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- README.md
- scripts/release/release.sh
Create official Docker image for the tool.
> Build and push docker image

- CONTRIBUTING.md
- README.md
- docs/USER_GUIDE.md
Overall improvements to documentation.
Fixes #291 
Fixes #292
Fixes #283
> Overall improvements to documentation

- .github/workflows/build.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- .github/workflows/validate.yaml
- Dockerfile
- README.md
- upgrade to go 1.14.6
- upgrade actions/setup-go to v2
- upgrade actions/checkout to v2
> Upgrade actions stages

- .github/dependabot.yaml
Describe what this pull request achieves. Ensure you have read the [Contributing Guidelines](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md) document before submitting.
> Add Docker to dependabot file

- .github/workflows/release.yaml
- scripts/build/build-all-osarch.sh
- scripts/release/release-note.sh
- scripts/release/release.sh
Enhance release scripts and fix issues reported by shellcheck.
> Enhance release scripts

- .github/workflows/release.yaml
Process of bumping homebrew formula was broken after we migrated to new organization which this fixes it.
> Fix homebrew PR creation process

- README.md
so that copy paste works
Adds missing `v` to the tag for latest version to the README so that copy-pasting will work.
Copy pasting of recommended install path was broken.
> add missing `v` to tag

- README.md
Add terraform-dosc' Slack workspace link.
> Add Slack workspace link

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Housekeeping improvement items:
- contributing guide
- issue template
- pull request template
> Improving contributing guide, issue and pull request template

- codecov.yml
> Enhance codecov process

- .github/workflows/build.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
Use correct docker registry (`quay.io`) in CI.
I have:
Let the CI run and make sure `build docker` job finishes properly.
> Use correct docker registry in CI

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
> Update Slack URL

- README.md
We recently started using GoReleaser for release workflow and to be able
to support all the use-cases (brew, scopp, etc) the preferred way of
assets distribution is gonna be a packaged format (tar.z and zip).
For the time being the standalone binary will also be included in GitHub
release assets, but will be deprecated in the upcoming releases.
I have:
> Update download instruction to use tar.gz

- go.mod
- go.sum
> Bump plugin-sdk to v0.1.0

- .github/workflows/release.yaml
> Fix release scripts for chocolatey

- .github/workflows/ci.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- go.mod
Updating to use go1.16 to support [darwin/arm64](https://golang.org/doc/go1.16#darwin) and build it accordingly with goreleaser.
Fixes #379
I have:
- test and build locally with go1.16 on a linux machine
- cross-compile `GOOS=darwin GOARCH=arm64` (it'd be nice if someone on M1 machine would be able to verify this)
> Update to go1.16

- Makefile
Following up https://github.com/terraform-docs/terraform-docs/pull/409#issuecomment-789063808
I have:
> Add ability to override go binary for make targets

- docs/user-guide/how-to.md
Applied recommended shellcheck changes to the example in the docs.
Fixes #422 
I have:
- [ x ] Read and followed terraform-docs' [contribution process].
- [ x ] All tests pass when I run `make test`.
Applied the proposed git hook to an example project.
> fix shellcheck warnings in git hook example

- .golangci.yml
- Makefile
- internal/cli/config.go
- internal/cli/reader.go
- internal/cli/run.go
- internal/cli/writer.go
- internal/format/tfvars_hcl.go
- internal/plugin/discovery.go
- internal/plugin/plugin.go
- internal/reader/lines.go
- internal/template/sanitizer.go
- internal/terraform/module.go
- internal/terraform/output.go
- internal/testutil/testing.go
- internal/types/types.go
- internal/types/types_test.go
- scripts/docs/generate.go
This PR upgrade golangci-lint to `v1.38.0` and configuration for more extensive issue detection and fixes the newly found issues.
I have:
Make sure both `make test` and `make lint` finish without error.
> Update golangci-lint and fix issues

- go.mod
- go.sum
> Bump plugin-sdk to v0.2.0

- .goreleaser.yml
As part of announcement made in v0.11.0, we're going to stop
distributing standalone binaries and only compressed files (either
tar.gz or zip) will be distributed and available to download from
GitHub Release page.
Fixes #454 
I have:
Not applicable.
> Do not distribute standalone binaries

- docs/user-guide/configuration.md
- go.mod
- go.sum
- internal/print/settings.go
> Add ShowDescription to Settings

- go.mod
- go.sum
Signed-off-by: Adam Johnson <adamjohnson01@gmail.com>
Fixes #473
I have updated go.mod to use the latest commit from terraform-config-inspect which resolves the issues seen in the issue above
I have:
I have build the binary and confirmed that it is working when run against config that contains configuration_aliases 
> Add support for configuration_aliases

- go.mod
- go.sum
> Bump plugin-sdk to v0.3.0

- .github/workflows/ci.yaml
- internal/cli/run_test.go
- internal/plugin/discovery.go
- internal/plugin/plugin.go
> Validate license header on files on CI

- docs/user-guide/configuration.md
- docs/user-guide/how-to.md
- docs/user-guide/installation.md
> Documentation cosmetic cleanup

- docs/user-guide/configuration.md
> Clarify deprecated settings in the docs

- .github/workflows/release.yaml
- Makefile
- scripts/release/release.sh
- scripts/release/update-choco.sh
> Enhance release scripts and Makefile

- .github/workflows/ci.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
- Dockerfile
> Update to go1.16.4

- .github/workflows/codeql.yaml
> Enable CodeQL scanning

- README.md
Signed-off-by: JB Beck <jb@scalr.com>
Adding Scalr's logo and a scalr.com link to the README as part of Scalr's sponsorship package
> Add Scalr sponsorship

- docs/user-guide/installation.md
Signed-off-by: Damans227 <Damans227@gmail.com>
Adds a new example to install documentation for macOs. Fixes Issue: https://github.com/terraform-docs/terraform-docs/issues/538 
I have:
Only test I ran is:  `make test`. It passed completely and generated following comments in the end:
```
coverage: 89.5% of statements
ok  	github.com/terraform-docs/terraform-docs/internal/types	0.203s	coverage: 89.5% of statements
?   	github.com/terraform-docs/terraform-docs/internal/version	[no test files]
?   	github.com/terraform-docs/terraform-docs/scripts/docs	[no test files]
```
> Add new example for MacOs Install docs

- Dockerfile
- scripts/release/Dockerfile
> Bump docker images (alpine and golang)

- internal/reader/lines.go
- internal/reader/lines_test.go
Fixes #555:
I have:
I added the test case in `TestReadLinesFromFile` which empty file(`testdata/empty.txt`) reads actually.
> Skip read lines from empty file

- README.md
- docs/developer-guide/plugins.md
- docs/how-to/pre-commit-hooks.md
- docs/user-guide/configuration.md
- docs/user-guide/configuration/content.md
- docs/user-guide/installation.md
- docs/user-guide/introduction.md
Update README and site documents.
Fixes #534
Fixes #547 
I have:
Not applicable.
> Overhaul README and docs improvements

- README.md
- docs/user-guide/configuration.md
- docs/user-guide/configuration/sections.md
Adjust typo, and suggest possible readability improvement, in README.
> docs: typo in README

- .editorconfig
- terraform/load.go
- terraform/load_test.go
- terraform/testdata/outputs-crlf/outputs.tf
- terraform/testdata/outputs-lf/outputs.tf
Always convert CRLF to LF in output description before generating the result. This will make sure the output result is always consistent.
Fixes #584 
I have:
Added new `TestLoadOutputsLineEnding` test cases.
> Always convert CRLF to LF for output description

- README.md
Remove Scalr sponsorship logo.
Fixes #667 
xref: #660
I have:
not needed
> Remove Scalr sponsorship

- .github/workflows/ci.yaml
- .github/workflows/codeql.yaml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yaml
Bump golang to 1.18.10.
I have:
* `make test`, see CI output
> Bump golang to 1.18.10

- docs/how-to/recursive-submodules.md
Fix spelling in recursive submodules docs
I have:
> Fix spelling

- README.md
Move terraform-docs bin in a folder already in the Linux PATH
I have:
In my Debian Bullseye
> Move terraform-docs bin in a folder already in the Linux PATH

- cmd/completion/completion.go
- cmd/completion/fish/fish.go
- docs/user-guide/installation.md
- internal/types/types.go
- Add completion of [fish shell](https://fishshell.com/)
- Cobra supports bash, zsh and fish, PowerShell
- I don't have windows environment, so I only add fish completion.
I have:
I actually built the source and verified that the completion appears on the command line on the fish shell.
> Add fish shell completion

- Dockerfile
- go.mod
- go.sum
This change upgrade the alpine base image used by terraform-docs from 3.18.2 to 3.19.0 and crypto golang library that have vulnerabilities.
Vulnerability Report before the changes:
```
terraform-docs:vuln (alpine 3.18.5)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
usr/local/bin/terraform-docs (gobinary)
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌─────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────┐
│       Library       │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                          Title                          │
├─────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼─────── …
```
> Fix crypto libraries vulnerabilities

- .github/workflows/cut-release.yml
- scripts/release/release.sh
> chore: add release-cut workflow

- .github/workflows/ci.yaml
- .github/workflows/prerelease.yaml
ci: Use correct env var for repo owner
> ci: Use correct env var for repo owner

- docs/how-to/pre-commit-hooks.md
Fix a typo (higly -> highly)
I have:
Did not run any tests since this does not change code.
> Update typo in pre-commit-hooks.md

- docs/how-to/insert-output-to-file.md
Two super simple typo fixes in one of the documentation pages.
I have:
N/A
> Fix typo in insert-output-to-file.md

- docs/user-guide/configuration/footer-from.md
- docs/user-guide/configuration/header-from.md
- terraform/load.go
- terraform/load_test.go
Adds .tofu to permitted file formats.
resolves #811 
I have:
tests pass.
> add support for .tofu files
